name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check Python version
        run: python --version

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Migrations
        run: python manage.py migrate

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test
        run: python manage.py test
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
      - name: Checkout master
        uses: actions/checkout@v2